# Generated by Django 4.2.6 on 2023-11-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="mainbackend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("menu", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("음식점", "음식점"), ("카페", "카페")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("phone", models.CharField(default="정보 없음", max_length=15)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
